services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: terra_api_dev
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/community?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./storage/media:/app/storage/media
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    container_name: terra_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: community
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d community"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine
    container_name: terra_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data_dev:
  redis_data_dev: